---
version: "3"
services:
  data-transport-layer:
    image: ethereumoptimism/data-transport-layer:${DTL_IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - ${SHARED_ENV_PATH}/data-transport-layer.env
      - .env
    ports:
      - ${DTL_PORT:-7878}:7878
    volumes:
      - dtl:/db
  l2geth-replica:
    image: ethereumoptimism/l2geth:${L2GETH_IMAGE_TAG:-latest}
    restart: unless-stopped
    entrypoint:
      - /bin/sh
      - -c
      #- "sleep infinity"
      - "/scripts/check-for-chaindata.sh && /scripts/l2geth-replica-start.sh"
    env_file:
      - ${SHARED_ENV_PATH}/l2geth-replica.env
      - .env
    ports:
      - ${L2GETH_HTTP_PORT:-9991}:8545
    volumes:
      - geth:/geth
      - ./kustomize/replica/bases/configmaps/:/scripts/
  replica-healthcheck:
    image: ethereumoptimism/replica-healthcheck:0.3.0
    restart: unless-stopped
    env_file:
      - kustomize/replica/envs/kovan/replica-healthcheck.env
      - .env
    volumes:
      - ./kustomize/replica/bases/configmaps/:/scripts/
volumes:
  dtl:
  geth:
