---
version: "3"
services:
  dtl:
    image: ethereumoptimism/data-transport-layer:${DTL_IMAGE_TAG:-latest}
    env_file:
      - ${PROJECT_NETWORK:-mainnet}/dtl.env
  l2geth:
    image: ethereumoptimism/l2geth:${L2GETH_IMAGE_TAG:-latest}
    env_file:
      - ${PROJECT_NETWORK:-mainnet}/l2geth.env
    ports:
      - ${L2GETH_HTTP_PORT:-8545}:8545
#     volumes:
#       - geth:/geth
# volumes:
#   geth: